# Generated by Django 5.1.2 on 2024-10-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_rename_machine_snackspot_machine_snackspot_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snackspot',
            name='position',
        ),
        migrations.AddField(
            model_name='snackspot',
            name='col',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='snackspot',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
