# Generated by Django 5.1.2 on 2024-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_snackspot_position_snackspot_col_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snackspot',
            name='image',
        ),
    ]
