# Generated by Django 5.1.2 on 2024-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_snackspot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackspot',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
